# syntax=docker/dockerfile:1

FROM node:18-slim AS builder

WORKDIR /app
COPY package.json package-lock.json ./

# Установить зависимости только из package-lock.json и без dev зависимостей
RUN npm ci
COPY . .
RUN npm run build

EXPOSE 3000

CMD ["npx", "serve", "build"]