// Code generated by ogen, DO NOT EDIT.
package api

type SendingFilterGetRes interface {
	sendingFilterGetRes()
}

type SendingGetRes interface {
	sendingGetRes()
}

type SendingPostRes interface {
	sendingPostRes()
}
