// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// PostcodesByCityGet implements GET /postcodes_by_city operation.
	//
	// Get information about postcodes in cities. Return map with `city` key and `postcode` array value.
	//
	// GET /postcodes_by_city
	PostcodesByCityGet(ctx context.Context) (PostcodesByCityGetResponse, error)
	// SendingGet implements GET /sending operation.
	//
	// Get information about a sending by `order_id`. Require a complete match of `order_id`. Return
	// `type`, `status` and `stages`.
	//
	// GET /sending
	SendingGet(ctx context.Context, params SendingGetParams) (SendingGetRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...Option) (*Server, error) {
	s, err := newConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
