// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// PostcodesByCityGet implements GET /postcodes_by_city operation.
//
// Get information about postcodes in cities. Return map with `city` key and `postcode` array value.
//
// GET /postcodes_by_city
func (UnimplementedHandler) PostcodesByCityGet(ctx context.Context) (r PostcodesByCityGetResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// SendingGet implements GET /sending operation.
//
// Get information about a sending by `order_id`. Require a complete match of `order_id`. Return
// `type`, `status` and `stages`.
//
// GET /sending
func (UnimplementedHandler) SendingGet(ctx context.Context, params SendingGetParams) (r SendingGetRes, _ error) {
	return r, ht.ErrNotImplemented
}
