// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"
)

type AddressPostcode int64

// Ref: #/components/schemas/Error
type Error struct {
	ErrorMessage string `json:"error_message"`
}

// GetErrorMessage returns the value of ErrorMessage.
func (s Error) GetErrorMessage() string {
	return s.ErrorMessage
}

// SetErrorMessage sets the value of ErrorMessage.
func (s *Error) SetErrorMessage(val string) {
	s.ErrorMessage = val
}

// Ref: #/components/schemas/PostcodesByCityGetResponse
type PostcodesByCityGetResponse map[string][]AddressPostcode

func (s *PostcodesByCityGetResponse) init() PostcodesByCityGetResponse {
	m := *s
	if m == nil {
		m = map[string][]AddressPostcode{}
		*s = m
	}
	return m
}

type SendingGetApplicationJSONBadRequest Error

func (*SendingGetApplicationJSONBadRequest) sendingGetRes() {}

type SendingGetApplicationJSONNotFound Error

func (*SendingGetApplicationJSONNotFound) sendingGetRes() {}

// Ref: #/components/schemas/SendingGetResponse
type SendingGetResponse struct {
	Type   SendingType    `json:"type"`
	Status SendingStatus  `json:"status"`
	Stages []SendingStage `json:"stages"`
}

// GetType returns the value of Type.
func (s SendingGetResponse) GetType() SendingType {
	return s.Type
}

// GetStatus returns the value of Status.
func (s SendingGetResponse) GetStatus() SendingStatus {
	return s.Status
}

// GetStages returns the value of Stages.
func (s SendingGetResponse) GetStages() []SendingStage {
	return s.Stages
}

// SetType sets the value of Type.
func (s *SendingGetResponse) SetType(val SendingType) {
	s.Type = val
}

// SetStatus sets the value of Status.
func (s *SendingGetResponse) SetStatus(val SendingStatus) {
	s.Status = val
}

// SetStages sets the value of Stages.
func (s *SendingGetResponse) SetStages(val []SendingStage) {
	s.Stages = val
}

func (*SendingGetResponse) sendingGetRes() {}

// Ref: #/components/schemas/SendingStage
type SendingStage struct {
	Name     SendingStageName `json:"name"`
	Date     time.Time        `json:"date"`
	Postcode AddressPostcode  `json:"postcode"`
	City     string           `json:"city"`
}

// GetName returns the value of Name.
func (s SendingStage) GetName() SendingStageName {
	return s.Name
}

// GetDate returns the value of Date.
func (s SendingStage) GetDate() time.Time {
	return s.Date
}

// GetPostcode returns the value of Postcode.
func (s SendingStage) GetPostcode() AddressPostcode {
	return s.Postcode
}

// GetCity returns the value of City.
func (s SendingStage) GetCity() string {
	return s.City
}

// SetName sets the value of Name.
func (s *SendingStage) SetName(val SendingStageName) {
	s.Name = val
}

// SetDate sets the value of Date.
func (s *SendingStage) SetDate(val time.Time) {
	s.Date = val
}

// SetPostcode sets the value of Postcode.
func (s *SendingStage) SetPostcode(val AddressPostcode) {
	s.Postcode = val
}

// SetCity sets the value of City.
func (s *SendingStage) SetCity(val string) {
	s.City = val
}

type SendingStageName string

const (
	SendingStageName_0 SendingStageName = "Принято в отделении связи"
	SendingStageName_1 SendingStageName = "Покинуло место приема"
	SendingStageName_2 SendingStageName = "Прибыло в сортировочный центр"
	SendingStageName_3 SendingStageName = "Покинуло сортировочный центр"
	SendingStageName_4 SendingStageName = "Прибыло в место вручения"
	SendingStageName_5 SendingStageName = "Вручено адресату"
)

// Ref: #/components/schemas/SendingStatus
type SendingStatus string

const (
	SendingStatus_0 SendingStatus = "В пути"
	SendingStatus_1 SendingStatus = "Доставлено"
	SendingStatus_2 SendingStatus = "Утеряно"
)

// Ref: #/components/schemas/SendingType
type SendingType string

const (
	SendingType_0 SendingType = "Письмо"
	SendingType_1 SendingType = "Посылка"
	SendingType_2 SendingType = "Бандероль"
)
