// Code generated by ogen, DO NOT EDIT.
package api

type DataImportSendingPostRes interface {
	dataImportSendingPostRes()
}

type EmployeeFilterGetRes interface {
	employeeFilterGetRes()
}

type SendingFilterGetRes interface {
	sendingFilterGetRes()
}

type SendingGetRes interface {
	sendingGetRes()
}

type SendingPostRes interface {
	sendingPostRes()
}
