version: "3.5"

services:
  client:
    container_name: "post_client"
    build: ./client
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: "post_backend"
    build: ./backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: "post_db"
    image: mongo:6.0.3
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: