version: "3.5"

services:
  client:
    container_name: "post_client"
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: "post_backend"
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: "post_db"
    image: mongo:6.0.3
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  swagger-ui:
    build:
      context: ./backend
      dockerfile: Dockerfile.spec
    ports:
      - "80:8080"
    environment:
      - SWAGGER_JSON=/spec/openapi.yaml
      - BASE_URL=/swagger

volumes:
  mongo_data: