version: "3.5"

services:
  client:
    container_name: "post_client"
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - backend

  backend:
    container_name: "post_backend"
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_POST=27017
    depends_on:
      - db

  db:
    container_name: "post_db"
    image: mongo:6.0.3
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./db/gold-samples:/samples

volumes:
  mongo_data:
